db:
  image: mysql:5.5
  ports:
    - "5001:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbpass
    - MYSQL_DATABASE=drupal
    - MYSQL_HOME=/etc
  volumes:
    - .docker/etc/my.cnf:/etc/my.cnf
  hostname: dbhost
  dns:
    - 8.8.8.8
    - 8.8.4.4
solr:
  hostname: solrhost
  image: ducdebreme/solr4_slim
  ports:
    - "5002:8983"
web:
  image: ducdebreme/bowline-web-php:5.5
  ports:
    - "5000:80"
  command: /start.sh
  environment:
    - COMPOSER_HOME=/.composer
  volumes:
    - .:/var/www
  links:
    - db:dbhost
    - solr:solrhost
  hostname: drupal
  dns:
    - 8.8.8.8
    - 8.8.4.4
