db:
  image: mysql:5.6
  ports:
    - "5001:3306"
  env_file: .env
  environment:
    - MYSQL_HOME=/etc
  volumes:
    - .docker/etc/my.cnf:/etc/my.cnf
  hostname: dbhost
  # dns:
  #   - 8.8.8.8
  #   - 8.8.4.4
solr:
  hostname: solrhost
  image: ducdebreme/solr4_slim
  volumes:
    - ./solr:/etc/conf/solr-index
    - ./solr-data:/var/solr/example/solr/collection1/data
  ports:
    - "5002:8983"
memcache:
  image: memcached
  expose: 
    - "11211"
web:
  hostname: drupal
  image: ducdebreme/php-drupal:5.6
  ports:
    - "5000:80"
  env_file: .env
  environment:
    - COMPOSER_HOME=/.composer
  volumes:
    - .:/var/www
    - ./.docker/etc/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
  links:
    - db:dbhost
    - solr:solrhost
    - memcache:memcache
  # dns:
  #   - 8.8.8.8
  #   - 8.8.4.4
