db:
  image: mysql:5.6
  ports:
    - "30001:3306"
  env_file: .env
  environment:
    - MYSQL_HOME=/etc
  volumes:
    - .docker/etc/my.cnf:/etc/my.cnf
  hostname: dbhost
  # dns:
  #   - 8.8.8.8
  #   - 8.8.4.4
solr:
  hostname: solrhost
  image: ducdebreme/solr4_slim
  volumes:
    - solr:/etc/conf/solr-index
    - solr-data:/var/solr/example/solr/collection1/data
  ports:
    - "30002:8983"
web:
  image: ducdebreme/php-drupal:5.6
  ports:
    - "30000:80"
  env_file: .env
  environment:
    - COMPOSER_HOME=/.composer
  volumes:
    - .:/var/www
    - .docker/etc/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
  links:
    - db:dbhost
    - solr:solrhost
  hostname: drupal
  # dns:
  #   - 8.8.8.8
  #   - 8.8.4.4
