db:
  image: mysql:5.5
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbpass
    - MYSQL_DATABASE=drupal
    - MYSQL_HOME=/etc
  volumes:
    - .docker/etc/my.cnf:/etc/my.cnf
  hostname: dbhost
  ports:
    - "6306:3306"
  dns:
    - 8.8.8.8
    - 8.8.4.4
web:
  image: ducdebreme/php-drupal:5.6
  environment:
    - COMPOSER_HOME=/.composer
  ports:
    - "6080:80"
  volumes:
    #- .docker/php-drupal/php.ini:/usr/local/etc/php/php.ini
    - .:/var/www
    # - .docker/web/apache.conf:/etc/apache2/sites-enabled/apache.conf
  links:
    - db:dbhost
  hostname: drupal
  dns:
    - 8.8.8.8
    - 8.8.4.4
